server:
  port: 8080
#选择要激活那个环境块
spring:
  profiles:
    active: dev

person:
  name: 张恒${random.uuid}
  age: ${random.int}
  email: 123
  happy: true
  birth: 2000/03/17
  maps: {k1: v1,k2: v2}
  list:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 3

dog:
  dog_name: 阿黄
  age: 3


---
server:
  port: 8090
# 模块名
spring:
  profiles: dev

---
server:
  port: 8099
spring:
  profiles: test